### PR TITLE
Add verisign DNS for when the ISP DNS is flaky

### PR DESCRIPTION
**Pull request by iMartyn**
So very oddly, the usage dns for the access nodes is broken at the minute, this _should_ help that by adding verisign (non-tracking public dns) to the head of the resolv.conf

I'd use google or opendns but I don't want to cause a diplomatic incident ;-)

### CODE REVIEW

**Comment by ultrafez** [comment]
Have you been able to verify that Debian will use that DNS server? I've had issues in the past with DNS config being specified in multiple places, leading to the wrong DNS server being used (issues with NetworkManager in particular).

Also: will this act as a fallback for ISP DNS, or will it prefer Verisign?

**Comment by iMartyn** [comment]
I believe (can't verify as the ansible is not generic enough for me to run through the whole thing just to fix this single issue) the server is using resolvconf and will put that .head file in.

I don't really see any way of testing it except suck it and see tbh.

It will set this as preferred dns, yes, but verisign dns is pretty rock solid (I use it at home).

**Comment by ultrafez** [comment]
Also: does this mean that `.hackspace` domains won't resolve on the server, as it's not using its own DNS? Or does this PR change the upstream DNS that our own DNS server recurses up to when it doesn't have the entry in its cache?

Sorry for the noob questions, I've never run my own DNS server before.

**Comment by ultrafez** [comment]
It's possible to test it by running Ansible on a VM, by the way - I had it working on my laptop at one point. I know it's a pain, but I just want to make sure we merge one fix rather than fix after fix until we get it right :)

**Comment by ultrafez** [comment]
Fair enough re: preferred DNS. Verisign are bound to be more reliable than whatever the ISP has cooked up.

**Comment by iMartyn** [comment]
Unless verisign starts responding for the .hackspace domain, even though it's the first in the list, the server will carry on to the following name servers until it gets no response.

I'm hoping that the nameservers are not hard-coded in the nameserver setup somewhere, so it may not fix the issue.  If they are, this won't make a blind bit of difference, but if they're not, we get a fixed internet :-)

I don't have time to test it, the laser is currently unable to read cards and it's open day on Saturday.  It's unfortunate but that's the situation.

**Comment by ultrafez** [comment]
Fair enough on all points, thanks for the explanation. LGTM.

**Comment by pbrook** [comment]
Err, why aren't we just using the prefectly good DNS server already running on that machine?
I'm pretty sure that's what gets handed out by the dhcp server.

**Comment by iMartyn** [comment]
If the server is recursing up all the way to the root server's, it's not
perfectly working.  If it's recursing to an upstream that isn't the system
resolver, then that upstream is broken and needs replacing. I assumed it
recursed to resolvconf, hence this attempt to fix broken dns.

**Comment by ultrafez** [comment]
I've done some reading about how `bind` should be configured for our use-case, and from what I now understand, we need to make some changes to what's in this PR. Most of the relevant info I got from [this article](https://www.digitalocean.com/community/tutorials/how-to-configure-bind-as-a-caching-or-forwarding-dns-server-on-ubuntu-14-04) which explained some of the different ways `bind` can be configured. Apologies if some of the following is a bit basic, it's partially there to aid my understanding.

The configuration in this PR won't help devices using our DNS to resolve domains any better, it'll only benefit domain resolution on the server itself (in that it will use Verisign instead of the ISP DNS).

Our DNS server needs to be running as a forwarding DNS server, meaning it will forward queries that it can't authoritatively answer (or fetch from its cache) to another nameserver (in this case, we want it to be Verisign). The configuration for a forwarding DNS is an extension of a caching DNS server (which will attempt to recursively resolve queries from the root servers downwards, and cache the results).

From looking at the `bind` configuration in this repo, it looks as though the `named.conf.options` file isn't modified from the default Debian `bind` config. This means that the DNS server isn't caching or forwarding (I'm not sure how it handles queries for domains besides `.hackspace` in that case). The changes we need to make are described in the article I linked above, but in a nutshell:

* Configure `bind` to allow caching by enabling recursion in `named.conf.options`, and adding an `allow-query` statement to allow devices on the local network to query it.
* Configure `bind` to forward queries it can't authoritatively answer, by adding Verisign to the `forwarders` section in `named.conf.options`, and adding a `forward only` statement to prevent it trying to resolve domains recursively if a forwarded query fails
* Modify `/etc/resolv.conf` to ensure it uses the local `bind` as the nameserver (however this apparently will be overwritten on reboot)
* Modify `/etc/network/interfaces` to set the `dns-nameservers` statement for the network adapter to point to our `bind` running locally, which overrides `/etc/resolv.conf` on reboot


That's how I see things from the best of my understanding, can you guys let me know if that sounds right?

**Comment by pbrook** [comment]
I don't understand why we need a forwarding server.

**Comment by ultrafez** [comment]
I'm not experienced on this subject, so I'll appeal your wisdom on this
one. If we didn't serve an authoritative response to the query, what should
happen?

**Comment by pbrook** [comment]
Well, so far I haven't seen a real description of what is broken, other than "we think it might be DNS".

**Comment by ultrafez** [comment]
The problem I saw was that when using the hackspace's DNS, some domains
would fail to resolve. The one that caused the real issue that prompted all
this was usage.ranyard.info, which is what the laser cutter's access node
needs to talk to. It failed to resolve for anybody using our DNS, and so
nobody could use the laser cutter.

On 10 Sep 2016 11:56, "Paul Brook" <notifications@github.com> wrote:

Well, so far I haven't seen a real description of what is broken, other
than "we think it might be DNS".

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/leedshackspace/lhs-marvin/pull/28#issuecomment-246105543>,
or mute the thread

**Comment by ultrafez** [comment]
After rebooting the server (with no configuration changes), the problem got worse, as the DNS refused to resolve anything it didn't have in its zone file. At least part of the issue was caused by the server having the incorrect time set - it was about 5 hours behind, and so a lot of DNSSEC negotiation was failing. What caused the clock to drift so much, I have no idea. However, ensuring that ntp could work (having a fallback DNS available on the server in case the server's own DNS wasn't working for whatever reason) seemed like a reasonably good idea.

**Comment by pbrook** [comment]
Huh, that's an entertaining failure mode. But given everything is going via the central server I'd be disappointed if using a forwarding resolver (v.s. resolving things itself) made any difference. Passing on "invalid" records seems like a fairly serious bug.

**Comment by ultrafez** [comment]
My wondering is whether there was some sort of failure with the ISP DNS, which caused queries to not resolve, and then that resolution failure got cached by the server for far too long somehow. It's an odd one - I agree with your point that configuring it as a forwarding resolver wouldn't fix the problem.

**Pull request merged**
